#pragma once

#define MASTER_LEFT

#ifdef RGB_MATRIX_ENABLE
    #define RGB_MATRIX_KEYPRESSES
    #define RGB_DISABLE_WHEN_USB_SUSPENDED
    #define RGB_MATRIX_FRAMEBUFFER_EFFECTS
    #define RGB_MATRIX_HUE_STEP 8
    #define RGB_MATRIX_SAT_STEP 8
    #define RGB_MATRIX_VAL_STEP 8
    #define RGB_MATRIX_SPD_STEP 10

    /* Activa todos los efectos RGB Matrix que quieras usar */ 

    #define ENABLE_RGB_MATRIX_TYPING_HEATMAP/// PARA EL MAIN 
    #define ENABLE_RGB_MATRIX_MULTISPLASH//PARA RAISE
    #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS//PARA GAMING
    #define ENABLE_RGB_MATRIX_BAND_VAL//PARA CONF
    #define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
    //#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE//GAMING
    //#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS//CRUCETA DONDE PRESIONO///////////////////
    //#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS//GAMING
    //#define ENABLE_RGB_MATRIX_MULTISPLASH//WAVES COLOR///////////////////////////////////
    //#define ENABLE_RGB_MATRIX_SOLID_SPLASH//WOVES 
#endif

#define SPLIT_LAYER_STATE_ENABLE
#define LAYER_STATE_16BIT

#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define TAPPING_TERM 175
#define TAPPING_TERM_PER_KEY
#define TAPPING_TOGGLE 1

// Ajuste inicial al encender
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#define RGB_MATRIX_STARTUP_HUE 180
#define RGB_MATRIX_STARTUP_SAT 255
#define RGB_MATRIX_STARTUP_VAL 200
#define RGB_MATRIX_STARTUP_SPD 32

#define SPLIT_TRANSPORT_MIRROR
